languageCode: en-us
title: A Sea of Sleep
baseURL: https://determined-bose-17e351.netlify.app/
theme: hugo-theme-massively
googleanalytics: ''
disqusShortname: ''
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
languages:
  en:
    languageName: English
