languageCode: en-us
title: A Sea of Sleep
baseURL: https://www.aseaofsleep.com/
theme: hugo-theme-massively
googleanalytics: ''
disqusShortname: ''
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
languages:
  en:
    languageName: English
